- .github/workflows/linux-build.yml
Enable OpenXR integration on Linux Build test on Github with "OpenXR tests" disabled
> Enable OpenXR integration on Linux Build test on Github

- cmake/GraphicsSample.cmake
- src/CMakeLists.txt
Since we're using `OpenXR-SDK-Source`, headers are generated at build time. We must look for them in the build directory, and add a dependency to the target that generates them.
The dependency was missing and the build directory was hardcoded.  Also fixed some formatting.
> Fix OpenXR include directory and CMake dependency

- include/ppx/application.h
- projects/04_cube_xr/main.cpp
- projects/fishtornado_xr/FishTornado.cpp
- src/ppx/application.cpp
- src/ppx/xr_component.cpp
Create a swapchain that is only for debug capture purpose, and present graphics queue on this debug swapchain in order to allow gpu debug tools (like renderdoc) to make captures.
> Add support for debug capture for XR

- src/ppx/grfx/vk/vk_device.cpp
The condition was inverted. I kept `ifndef` instead of just `ifdef` because of consistency with others in the same file.
This problem only caused a build failure with old SDKs.
> Fix Vulkan 1.3 ifdef

- CMakeLists.txt
- include/ppx/application.h
- include/ppx/grfx/grfx_swapchain.h
- include/ppx/xr_component.h
- projects/04_cube_xr/main.cpp
- projects/fishtornado_xr/FishTornado.cpp
- projects/fishtornado_xr/Flocking.cpp
- src/ppx/application.cpp
- src/ppx/grfx/dx11/dx11_swapchain.cpp
- src/ppx/grfx/dx12/dx12_swapchain.cpp
- src/ppx/grfx/grfx_swapchain.cpp
- src/ppx/grfx/vk/vk_swapchain.cpp
- src/ppx/xr_component.cpp
Vulkan and D3D11 coming next.
Some misc fixes too:
- Comments and formatting.
- Put all the XR settings into its own `xr` struct.
- Disabled annoying warning with MSVC for unscoped enums. They're used everywhere also due to dependencies.
> [D3D12] Add XR depth swapchain and submit depth images each frame.

- docs/building_and_running.md
`cmake_path` is introduced in cmake version 3.20. Using older cmake will result in error.
> update doc about cmake version

- include/ppx/grfx/grfx_instance.h
- src/ppx/application.cpp
The original crash comes from the device creation failed to load "VK_KHR_swapchain" extension, so the function call to create swapchain failed. This fix the issue which allows Nsight Graphics to do captures for the XR application.
> Fix the crash when enable XR debug capture.

- CMakeLists.txt
- benchmarks/render_target/main.cpp
- projects/16_gbuffer/Material.cpp
- src/CMakeLists.txt
Fixing some warning on the linux version:
-  `-Wnullability-completness` disabled, from third-party code.
-  `-Wdeprecated-anon-enum-enum-conversion` disabled, from third-party code.
- fix uint32_t bad append to a string.
- compile xxHash C code as C, not C++. (this was done a long time ago because some buildsystem was complaining).
> fix warnings

- include/ppx/grfx/grfx_constants.h
- src/ppx/graphics_util.cpp
- src/ppx/grfx/dx11/dx11_command_list.cpp
- src/ppx/grfx/dx12/dx12_command.cpp
This loads all mipmap levels in a DDS file into a single staging buffer and then copies those into an image from there. There's a slight optimization possible where Vulkan's `CopyBufferToImage` lets you use copy all regions using only a single command; for readability I've split that into a separate PR that I'll follow up with.
Fixes #32
> Load mipmaps from DDS files

- include/ppx/grfx/dx11/dx11_command.h
- include/ppx/grfx/dx12/dx12_command.h
- include/ppx/grfx/grfx_command.h
- include/ppx/grfx/grfx_queue.h
- include/ppx/grfx/vk/vk_command.h
- src/ppx/graphics_util.cpp
- src/ppx/grfx/dx11/dx11_command.cpp
- src/ppx/grfx/dx12/dx12_command.cpp
- src/ppx/grfx/grfx_queue.cpp
- src/ppx/grfx/vk/vk_command.cpp
Batch calls for `CopyBufferToImage`. This has the most apparent benefit in Vulkan, where `vkCmdCopyBufferToImage` takes a `regions` argument and can copy all mip levels from a single buffer into the image with a single API call. However, it also reduces the number of calls in DirectX 12, by going from something like
```
StartCommand()
TransitionImageLayout()
CopyTextureRegion()
TransitionImageLayout()
EndCommand()
StartCommand()
TransitionImageLayout()
CopyTextureRegion()
TransitionImageLayout()
EndCommand()
StartCommand()
TransitionImageLayout()
CopyTextureRegion()
TransitionImageLayout()
EndCommand()
StartCommand()
TransitionImageLayout()
CopyTextureRegion()
TransitionImageLayout()
EndCommand()
```
to
```
StartCommand()
TransitionImageLayout()
CopyTextureRegion()
CopyTextureRegion() …
```
> Reduce API calls for CopyBufferToImage

- include/ppx/grfx/dx11/dx11_command.h
- include/ppx/grfx/dx12/dx12_command.h
- include/ppx/grfx/grfx_command.h
- include/ppx/grfx/vk/vk_command.h
- src/ppx/grfx/dx11/dx11_command.cpp
- src/ppx/grfx/dx12/dx12_command.cpp
- src/ppx/grfx/vk/vk_command.cpp
Take a pointer instead of a reference. Note: I agree that it's better to take a reference to protect against `nullptr`, but we should probably do that as a single mass refactor.
This also fixes a build problem in our internal build: `{pCopyInfo}` is not actually constructing a vector (and the function is called in an infinite loop).
> Change CopyBufferToImage signature to match other methods

- projects/fishtornado/FishTornado.cpp
Storage images are used by the flocking code. This bug seems only to trigger on Pixel 6 Pro ICDs and not on PC desktop ICDs
> Fix fishtornado bug of having descriptor pool of insufficient size

- tools/pack_glb.py
I have another script that uses this as a library as part of the process of compressing all images and then packing them into a GLB, but this works standalone as well. I split up the commits for PR readability and because we haven't decided on exactly what extension and container format to use for compressed images.
> Add a pack_glb utility to create glb files from GLTF

- .gitignore
- cmake/GraphicsSample.cmake
The change allows, among other things, samples to share code between C++ and shaders (e.g. struct definitions or bindings).
Also edited .gitignore to ignore tags files from ctags.
> Added support for custom include directories in samples

- benchmarks/headless_compute/main.cpp
- include/ppx/application.h
- include/ppx/command_line_parser.h
- include/ppx/grfx/dx11/dx11_swapchain.h
- include/ppx/grfx/dx12/dx12_swapchain.h
- include/ppx/grfx/grfx_swapchain.h
- include/ppx/grfx/vk/vk_swapchain.h
- src/CMakeLists.txt
- src/ppx/application.cpp
- src/ppx/command_line_parser.cpp
- src/ppx/grfx/dx11/dx11_swapchain.cpp
- src/ppx/grfx/dx12/dx12_device.cpp
- src/ppx/grfx/dx12/dx12_swapchain.cpp
- src/ppx/grfx/grfx_swapchain.cpp
- src/ppx/grfx/vk/vk_swapchain.cpp
To run an application in headless mode, pass the `--headless` flag. All APIs are supported. Software rendering also supports this mode.
In headless mode, no window or graphics surface is created. The graphics swapchain is created and managed manually, i.e. the render targets (color images) and depth images are created explicitly. The `Present` and `AcquireNextImage` calls are also handled manually by submitting empty command buffers that signal or wait for semaphores as needed.
Additional changes:
* Explicitly set severity of D3D12 debug message, and ignore the non-matching clear value warnings that cannot be avoided in headless mode. They are noisy, performance-only warnings.
* Add a CMake option to the Linux build to avoid linking to XCB if only headless execution is desired …
> Add an option to run an application in headless mode.

- include/ppx/grfx/dx11/dx11_device.h
- include/ppx/grfx/dx12/dx12_device.h
- include/ppx/grfx/grfx_device.h
- include/ppx/grfx/vk/vk_device.h
- src/ppx/grfx/dx11/dx11_device.cpp
- src/ppx/grfx/dx12/dx12_device.cpp
- src/ppx/grfx/vk/vk_device.cpp
Independent blending is automatically enabled in DX11 and DX12 at pipeline creation when using blend states (see GraphicsPipeline::InitializeBlendState in dx12_pipeline.cpp).
In Vulkan, independent blending is handled at device creation (via vkPhysicalDeviceFeatures), and is never enabled, which creates a discrepancy of behavior between Vulkan and DirectX.
This discrepancy is fixed by the current PR in the following way.
* Enabled independent blending in Vulkan when available
* Added a new method to the device class to check whether independent blending is supported or not
> Independent blending in Vulkan

- src/ppx/grfx/vk/vk_pipeline.cpp
In Vulkan's blend states initialization, the alpha blend factor was used instead of the color blend factor for the destination, causing bugs in any blend state using different factors for alpha and color.
> Fixed a bug in Vulkan handling of blend states

- include/ppx/bitmap.h
- include/ppx/graphics_util.h
- projects/15_basic_material/main.cpp
- projects/16_gbuffer/Material.cpp
- projects/16_gbuffer/main.cpp
- projects/fishtornado/FishTornado.cpp
- projects/fishtornado/Ocean.cpp
- projects/fishtornado_xr/FishTornado.cpp
- projects/fishtornado_xr/Ocean.cpp
- src/ppx/bitmap.cpp
- src/ppx/graphics_util.cpp
Currently, `Bitmap::Fill` takes a float array and converts to integer when needed. This is undefined behavior as the desired integer value may not be representable in floating point.
This PR changes `Bitmap::Fill` to take a templated type instead. The helper `CreateTexture1x1` is also changed to allow the caller to specify the data type (which will be used to determine the type of the underlying texture too).
> Rework Bitmap::Fill to avoid undefined behavior

- projects/23_async_compute/main.cpp
The imageAcquire semaphore is not waited on. This should fix the validation error we have on some GPUs.
Fixes #40
Signed-off-by: Nathan Gauër <brioche@google.com>
> async compute: fix semaphore not awaited

- projects/20_camera_motion/main.cpp
`DrawInstructions` uses ImGui commands without checking whether it's disabled. 
It should be called within the standard `DrawDebugInfo` that checks for that.
> Fix use of a sample's ImGui commands when it could be disabled

- include/ppx/command_line_parser.h
- src/ppx/application.cpp
- src/ppx/command_line_parser.cpp
- src/test/command_line_parser_test.cpp
BigWheels allow setting the output directory, but generates the filename.
This limits our options as we cannot write to arbitrary files (memfd?) to integrate bigwheels into other applications.
> cli: add --screenshot-filepath option

- cmake/ShaderCompile.cmake
- src/ppx/grfx/vk/vk_descriptor.cpp
In Vulkan, arrays are flattened at descriptor layout creation, i.e. they are turned into as many descriptors of size 1 as the size of the original array. However, flattened arrays were not fully supported in the rest of code. This PR addresses the issues with two following fixes.
* Added a compiler option to flatten arrays
* Took "arrayIndex" into account when updating the descriptor sets
> Fixed shader array support in Vulkan

- assets/benchmarks/shaders/Benchmark.hlsli
- assets/benchmarks/shaders/Benchmark_Diffuse.hlsl
- assets/benchmarks/shaders/Benchmark_PbrMetallicRoughness.hlsl
- assets/benchmarks/shaders/CMakeLists.txt
- projects/benchmark/CMakeLists.txt
- projects/benchmark/main.cpp
This is a first requirement for this benchmark: allow us to have multiple shaders running and swap them at runtime, or not.
The PBR code is taken from the 28_gltf sample, but common parts are moved to a shared file.
The idea is to share the same set of inputs across all shaders for this benchmark, simplifying the pipeline layout handling.
> benchmark: add ability to change shader on the fly

- projects/15_basic_material/main.cpp
- projects/16_gbuffer/main.cpp
- projects/fishtornado/FishTornado.cpp
- projects/fishtornado_xr/FishTornado.cpp
- src/ppx/application.cpp
uint64_t is always 64 bits, but implemented using either `unsigned long` (x64), or `unsigned long long` (x86). This causes issues with the printf format specifier.
This is now an issue as we enforce -Werror by default.
> misc: fix format specifier for uint64_t

- assets/oit_demo/shaders/BufferBucketsCombine.hlsl
- assets/oit_demo/shaders/BufferBucketsGather.hlsl
- assets/oit_demo/shaders/CMakeLists.txt
- assets/oit_demo/shaders/Common.hlsli
- include/ppx/grfx/dx12/dx12_device.h
- include/ppx/grfx/grfx_device.h
- include/ppx/grfx/vk/vk_device.h
- projects/oit_demo/Buffer.cpp
- projects/oit_demo/CMakeLists.txt
- projects/oit_demo/DepthPeeling.cpp
- projects/oit_demo/OITDemoApplication.cpp
- projects/oit_demo/OITDemoApplication.h
- projects/oit_demo/README.md
- projects/oit_demo/WeightedAverage.cpp
- src/ppx/grfx/dx12/dx12_device.cpp
- src/ppx/grfx/grfx_draw_pass.cpp
- src/ppx/grfx/vk/vk_device.cpp
* Added the first buffer-based algorithm (buckets)
* Added a way to find out if the hardware supports fragment shader stores and atomics
* Fixed an issue that was preventing the creation of a draw pass without depth/stencil
* Performed some code clean up based on the previous PR comments
> Added a new algorithm to the OIT sample

- include/ppx/bitmap.h
- src/ppx/bitmap.cpp
This change adds a variant of the Bitmap::Create functions for external storage to take a custom row stride for cases where the row stride is not width * pixel stride.
> Adds custom row stride version of Bitmap::Create

- src/ppx/graphics_util.cpp
This chagne fixes an issue with the CopyBitmapToImage function that corrects an assumption that the number of pixels copied is always the row stride.
- Fixed row stride calculation for staging buffer.
- Changed number of bytes copied to b based on the bitmap's width and not the row bytes.
> Fixed copy size and row stride calculations

- src/test/ppm_export_test.cpp
> Use signed char in PPM test when building texel array

- include/ppx/application.h
This prevents build failures in our internal build system.
> Include <cinttypes> to get standard definitions for PRIu64 and PRId64.

- include/ppx/application.h
- src/android/MainActivity.java
- src/android/main.cpp
This uses [Intent extras](https://developer.android.com/reference/android/content/Intent#getExtras()) to allow the Android application to be started over ADB with additional arguments.
For example:
```sh
adb shell am start -n com.google.bigwheels/.MainActivity -e arguments "--help"
```
> Add command line args to Android builds.

- projects/15_basic_material/main.cpp
The bad pipeline didn't seem to have an issue on NVIDIA. But on AMD whatever the internal defaults are was causing the geometry to not get drawn.
> Fixed bad pipeline that wasn't drawing correctly on AMD

- src/CMakeLists.txt
- src/ppx/application.cpp
- src/ppx/imgui_impl.cpp
ImGui renders, but the aspect ratio is wrong.
We should get the Android Window size instead of hard code 720p.
> Enable ImGui on Android.

- CMakeLists.txt
- build.gradle
- cmake/GraphicsSample.cmake
- include/ppx/base_application.h
- include/ppx/fs.h
- include/ppx/grfx/grfx_swapchain.h
- include/ppx/xr_component.h
- src/CMakeLists.txt
- src/android/MainActivity.java
- src/android/main.cpp
- src/ppx/fs.cpp
- src/ppx/xr_component.cpp
NativeActivity is supported since a long time. GameActivity is the new recommended method.
THe issue is GameActivity is not supported by Android, and being brand new means lack of support in other domains.
Moving back to NativeActivity is a risk, if it suddenly gets deprecated. But the cost of the switch being lower than the cost of fixing dependencies to use GameActivity means it's an acceptable risk.
> android: switch back to NativeActivity.

- build.gradle
All the samples shared the same ID, meaning we could only install one sample at the time on a device. This should solve the issue.
> android: fix app ID on android

- include/ppx/application.h
- include/ppx/window.h
- src/CMakeLists.txt
- src/ppx/application.cpp
- src/ppx/imgui_impl.cpp
- src/ppx/window.cpp
- src/ppx/window_android.cpp
- src/ppx/window_glfw.cpp
- So we can remove 20 of `#if defined`
- Remove platform specific clutter from Application
> Add abstraction for platform window operations.

- build.gradle
So that only the library needed for the sample is built and packaged
> Android: specify project specific targets in the build

- build.gradle
- src/android/AndroidManifest.Quest.xml
- src/android/AndroidManifest.XR.xml
- src/android/AndroidManifest.xml
The initial method I found was using resource strings. But we can actually replace them at compile-time using those placeholder variables. This would simplify integration with other build-systems.
> android: change how we replace manifest values

- include/ppx/application.h
- src/android/main.cpp
- src/ppx/window_android.cpp
I got a bit annoyed at `#if defined` statements, and trying to figure out what is the exact control flow, so I pulled out the part that are glfw or android specific
The new stuff
* Actually have a proper Android event loop
* Use Android screen size, instead of hardcoded 720p horizontal resolution
* ImGui input
> Event loop implementation for Android.

- .github/workflows/android-build.yml
- docs/ci_testing.md
Builds a single sample for mobile - Gbuffer
I think we could also combine all CI checks (windows, linux, android) into a single workflow with multiple jobs. But since the existing linux and windows are 2 different workflows, I created a new one for now 
Fixes https://github.com/google/bigwheels/issues/118
> Add a new workflow to check if Android builds

- src/ppx/imgui_impl.cpp
GLFW does not support the Android platform, so this change removes the header file from being referenced when building for Android.
> Remove GLFW from Android builds.

- .github/workflows/android-build.yml
There seems to be a vulnerability fixed in 2.4.2.
> Explicitly set the gradle build action version

- benchmarks/compute_operations/main.cpp
- benchmarks/render_target/main.cpp
- benchmarks/texture_transfer_cpu_to_gpu/main.cpp
- projects/01_triangle/main.cpp
- projects/02_triangle_spinning/main.cpp
- projects/03_square_textured/main.cpp
- projects/04_cube/main.cpp
- projects/05_cube_textured/main.cpp
- projects/06_compute_fill/main.cpp
- projects/07_draw_indexed/main.cpp
- projects/11_compressed_texture/main.cpp
- projects/22_image_filter/main.cpp
- projects/27_mipmap_demo/main.cpp
It's used by some samples already.
Some benchmark has more complicated logic regarding viewport size, so they are left alone.
> Use Application::{GetScissor,GetViewport}().

- projects/01_triangle/main.cpp
Those members were removed in #148, but forgotten here. Fixing this.
> fix 01_triangle GetViewport()/GetScissor()

- include/ppx/bitmap.h
- include/ppx/fs.h
- include/ppx/mipmap.h
- include/ppx/tri_mesh.h
- src/ppx/bitmap.cpp
- src/ppx/fs.cpp
- src/ppx/graphics_util.cpp
- src/ppx/mipmap.cpp
- src/ppx/tri_mesh.cpp
Adds a number of performance tweaks to the loading process. This brings down the load for fishtornado on a Quest2 headset from ~30-40s to ~5-6s.
> Performance Tweaks

- build.gradle
- src/ppx/application.cpp
- src/ppx/graphics_util.cpp
- src/ppx/mipmap.cpp
This fixes #140.
- Updated IBL loading work properly on Android, not the most efficient method but that will be addressed in a follow up PR.
- Added logging to show long an application Setup() takes for easier eyeball benchmarking.
- Added 15_basic_material to Android samples.
> Fix for 15_basic_material on Android

- include/ppx/grfx/vk/vk_config_platform.h
- src/ppx/grfx/vk/vk_device.cpp
Set `VMA_VULKAN_VERSION` to explicitly compile VMA for Vulkan 1.2 and below.
[VMA Docs](https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/quick_start.html#quick_start_initialization_selecting_vulkan_version).
> Explicitly set the VMA VK version.

- build.gradle
- cmake/GraphicsSample.cmake
- src/android/AndroidManifest.Quest.xml
This removes the `quest` target's dependency on the Oculus OpenXR SDK.
> Remove static Oculus loader for the shared loader.

- assets/materials/shaders/CMakeLists.txt
- assets/oit_demo/shaders/CMakeLists.txt
- cmake/ShaderCompile.cmake
- src/CMakeLists.txt
So that they are displayed consistently everywhere
> Use spaces instead of tabs in cmake files

- include/ppx/profiler.h
- src/android/main.cpp
- src/ppx/profiler.cpp
Android activities lifecycles are not what we expect on desktop platforms:
- we can be paused/stopped/restarted.
- the window can be destroyed & recreated during execution.
BigWheels assumes you start once, and exit once. So the whole swapchain, initialization cannot handle android lifecycle events. Handling Android lifecycle events could either mean a deep, fine-grained integration, or what I'm implementing here.
This implementation hides the whole lifecycle concept to the application. Meaning we can have a simple, linear code when writing samples.
The downside is we cannot handle PAUSE like a real app does: our whole state is reset. I believe this downside is OK for the simplification this solution brings.
For now, I hard-assert on all messages handled in the default handler so we …
> android: fix lifecycle handling

- src/test/knob_test.cpp
A fix for stricter knob framework unit tests that require specifying template arguments in declarations.
> Fix knob framework unit tests

- include/ppx/application.h
- projects/10_cube_map/main.cpp
- projects/12_shadows/main.cpp
- projects/13_normal_map/main.cpp
- projects/14_input/main.cpp
- projects/15_basic_material/main.cpp
- projects/16_gbuffer/main.cpp
- projects/20_camera_motion/main.cpp
- projects/22_image_filter/main.cpp
- projects/23_async_compute/main.cpp
- projects/27_mipmap_demo/main.cpp
- projects/fishtornado/FishTornado.cpp
- projects/fishtornado/FishTornado.h
- projects/fishtornado_xr/FishTornado.cpp
- projects/fishtornado_xr/FishTornado.h
- src/ppx/application.cpp
Instead of `ppx::Application::DrawDebugInfo` accepting a callback to display additional info through ImGui, the callback has been converted into a method called `DrawGui`. This makes it quick to override, and keeps the projects consistent.
> Promote ImGui debug info callback to lifecycle method.

- benchmarks/compute_operations/main.cpp
- benchmarks/draw_call/main.cpp
- benchmarks/headless_compute/main.cpp
- benchmarks/overdraw/main.cpp
- benchmarks/primitive_assembly/main.cpp
- benchmarks/render_target/main.cpp
- benchmarks/texture_load/main.cpp
- benchmarks/texture_sample/main.cpp
- benchmarks/texture_transfer_cpu_to_gpu/main.cpp
- include/ppx/csv_file_log.h
- src/ppx/csv_file_log.cpp
This change moves CSVFileLog to use filesystem::path for its target, rather than std::string. This is because filesystem::path.c_str() resolves to wchar_t on MSVC, and char on other compilers, making it difficult to pass a filename processed via filesystem::path into the function otherwise.
> Move CSVFileLog to use filesystem::path

- src/ppx/graphics_util.cpp
So we will get a error message instead of crashing in vkCmdCopyBufferToImage.
fyi: @elviscapiaq
> Add assertion for cubemap dimension.

- gradle.properties
The Android build started to fail due to out of heap memory errors.
The Github default runners have 7Gb or Ram and 14Gb of SSD.
Bumping to 4G should still allow the build to run on the default runners while fixing local builds.
> build: bump android build ram usage limit

- include/ppx/application.h
- include/ppx/command_line_parser.h
- src/ppx/application.cpp
- src/ppx/command_line_parser.cpp
This change introduces the 'run-time-ms' parameter which dictates how long to run a bigwheels application for before automatically quitting. It also cleans up a little bit around the use of timestamps and MaxFrames.
> Add runtime parameter to limit test in realtime; fix frame-count argument to use 0 as infinite.

- src/ppx/application.cpp
ImGUI itself is not non-deterministic. But ImGUI is used to display metrics or data which is not deterministic.
I don't see a benefit in keeping imgui in deterministic mode, so the simplest option seem to disable it.
> application: disable imgui on deterministic runs.

- include/ppx/fs.h
- src/ppx/bitmap.cpp
- src/ppx/fs.cpp
- src/test/CMakeLists.txt
- src/test/filesystem_test.cpp
Android has 2 ways to access assets:
- the Assets NDK API
- normal disk read. Desktop only has the latter.
The FS API built today was preventing Android to load assets from the disk, and API diverged a bit (ex memory-mapped usage was Android only).
This commit tried to re-uniformize this. To limit the PR scope, the memory mapping is not added for desktop, but is trivial to add now.
Adding this code would also unblock Android application to load assets not from the APK folder, but from the disk. The issue I had was APK/disk duality is only valid on desktop.
I solved this by assuming relative path on Android means in-APK, and absolute means "I know what I'm doing, disk access".
This seems to work for most use-cases I found, but we might need to revisit this in the future if need be.. Maybe …
> fs: tries to uniformize Android/Desktop FS ops.

- include/ppx/timer.h
- projects/fishtornado/FishTornado.cpp
- projects/fishtornado_xr/FishTornado.cpp
- src/ppx/application.cpp
- src/ppx/graphics_util.cpp
- src/ppx/timer.cpp
A lot of timer patterns we have is start, do something, and stop in the same function to measure some process.
The Scopedtimer wraps this logic in a class using RAII. An alternative implementation could be to not print, but use a float& which is set to the elapsed time in the destructor. This would allow more control over the format, and print additional info not available on timer initialization.
But for now, this is a simple pattern we can start with.
> utils: add ScopedTimer class.

- include/ppx/knob.h
- src/ppx/knob.cpp
- src/test/knob_test.cpp
* Replace `GetFlagHelpText()` with storing help parameters separately and assembling in `KnobManager::GetUsageMsg()`
* Move `KnobCheckbox` member functions to `knob.cpp`
* When listing `KnobDropdown` choices in usage message, only add quotation marks if there are spaces
* Made KnobManager a friend class of Knob and removed some of the getters/setters, preferring to have protected/private members where possible
* Renamed `SetFlagDesc` -> `SetFlagDescription`
> Minor improvements for knob framework

- include/ppx/metrics.h
- src/ppx/application.cpp
- src/ppx/metrics.cpp
This set of changes includes two key pieces:
1. The report object is now internal to the manager, as the lifetime of strings used by the json object cannot be guaranteed outside of the scope of the manager regardless. This cleans up the application-side piece of the report writing.
2. Unique_ptrs are now used for the metrics. This helps clean up several pieces of the metrics code, especially around destructors and constructors.
> Cleanup Metrics - Pull Report internal to Manager and use unique_ptrs

- README.md
The building page uses Ninja to build, so changing the readme instructions on how to run tests assuming the build instructions were followed
> Update instructions on how to run tests

- src/ppx/knob.cpp
Reorder initializer list for KnobCheckbox so that it's in the same order as the class members
> Reorder initializer list for KnobCheckbox

- include/ppx/command_line_parser.h
- src/ppx/application.cpp
- src/ppx/command_line_parser.cpp
BigWheels applications try to guess assets locations from the executable directory.
This is fine for desktop, and most basic use cases.
When using BigWheels to run tests, we might want to swap assets between each run, to test different versions of shaders by ex.
On desktop, we were able to do that by changing the assets in the correct directory.
On Android however, the APK contains the assets. This means swapping assets requires a new APK compilation.
This new flags would allow us to add arbitrary asset paths to the search list, allowing a quick asset-swap without having to rebuild APKs.
> Add a new `--assets-path` flag to applications.

- projects/fluid_simulation/shaders.h
Remove superfluous std::move (-Werror,-Wpessimizing-move).
> remove std::move from return

- projects/fluid_simulation/sim.cpp
- projects/fluid_simulation/sim.h
GetElapsedTime() works well with --deterministic.
Timers don't.
But in this case, maybe removing deltatime computation entirely is fine?
> fluidsim: remove sources of non-determism

- include/ppx/application.h
- projects/16_gbuffer/Entity.cpp
- projects/fishtornado/FishTornado.cpp
- projects/fishtornado/Flocking.cpp
- projects/fishtornado/Ocean.cpp
- projects/fishtornado/Shark.cpp
- projects/fishtornado_xr/FishTornado.cpp
- projects/fishtornado_xr/Flocking.cpp
- projects/fishtornado_xr/Ocean.cpp
- projects/fishtornado_xr/Shark.cpp
- projects/fluid_simulation/shaders.cpp
- src/ppx/application.cpp
- src/ppx/base_application.cpp
LoadShader take a subdir, and a shader name. Those 2 are then combined, and GetAssetPath is called.
2 Samples however called GetAssetPath on the subdir before. This was fine as long as the path returned was absolute because std::filesystem::path ignores the first part when
concatenating to an absolute path:
```
"/tmp/titi/" / "/tmp/toto" == "/tmp/toto"
"/tmp/titi/" / "tmp/toto" == "/tmp/titi/tmp/toto"
```
Now what we use "--assets-path", the asset dir could be relative, and this bugs becomes visible.
> samples: fix asset paths loading for some samples

- src/ppx/base_application.cpp
The pattern we use if `LoadFile(GetAssetPath("asset/toto"))`. If GetAssetPath fails, "" is returned, making LoadFile show this message:
*** PPX ASSERT ***
Message   : could not load file: ""
Condition : false
This is useless, as it doesn't tells us which asset failed. This commits adds en assert in GetAssetPath() in case it returns "". Giving us this message:
*** PPX ASSERT ***
Message   : Could not find valid path for asset "basic/shaders/spv/StaticVertexColors.vs.spv"
Condition : !assetPath.empty()
Function  : GetAssetPath
> Improves bad asset path error message.

- README.md
Cmake option was renamed a while ago, but it looks like documentation hasn't been updated.
> Update documentation on how to turn off tests

- .github/workflows/android-build.yml
- .gitignore
- build.gradle
- docs/building_and_running.md
- gradle.properties
- projects/01_triangle/build.gradle
- projects/04_cube/build.gradle
- projects/04_cube_xr/build.gradle
- projects/08_basic_geometry/build.gradle
- projects/15_basic_material/build.gradle
- projects/16_gbuffer/build.gradle
- projects/fishtornado/build.gradle
- projects/fishtornado_xr/build.gradle
- settings.gradle
Use multi-project build setup instead of build flavours for samples. The root project `build.gradle` specifies how to build, and each subproject just creates a copyTask to copy assets that are used by the project.
Updates/benefits:
- In Android Studio, easier way to find and switch samples and no gradle sync when switching build flavours
- In CLI more straightforward way to discover projects and no need to remember syntax on how to build.
- Specifies assets per project, resulting in smaller APKs. Third party assets are only used in a few projects, and those are very large (> 300 MB). No need to add them to projects that don't use them.
- Instead of split APKS use abi filters to only build for arm64-v8a
- Build all samples in the github CI
- Modifies the default location of build and .cxx …
> Update Android build to use multi-project setup

- include/ppx/command_line_parser.h
- src/ppx/command_line_parser.cpp
Includes two changes:
1. Creates a default-true behavior on flags when they're present, so they can also now be explicitly set to false. E.g.:
--argument present means true
no --argument present means "use internal default" (most likely false)
--argument=true means explicitly true
--argument=false means explicitly false
2. Cleans up the CLI help to be 80 characters wide, and unifies the strings used between XR/non-XR versions. Also alphabetizes the order of arguments. To do this, xr-ui-resolution is now xr-ui-res.
> Fix some minor CLI nits

- include/ppx/application.h
- include/ppx/command_line_parser.h
- include/ppx/metrics.h
- src/ppx/application.cpp
- src/ppx/command_line_parser.cpp
- src/ppx/metrics.cpp
This set of changes introduces the following metrics command-line arguments:
1. enable-metrics, to enable/disable the metrics globally.
2. metrics-filename, which allows a user to set a destination path and filename for the metrics report.
3. overwrite-metrics-file, which allows a user to overwrite any existing metrics file, as set by metrics-filename.
It also includes some minor cleanup in the METRICS_NO_COPY macro.
> Add CLI flags for controlling metrics enable/disable, filename, etc.

- include/ppx/grfx/dx12/dx12_command.h
- include/ppx/grfx/grfx_command.h
- include/ppx/grfx/vk/vk_command.h
- projects/24_push_constants/PushConstants.cpp
- projects/26_push_descriptors/PushDescriptors.cpp
- src/ppx/grfx/dx12/dx12_command.cpp
- src/ppx/grfx/vk/vk_command.cpp
This change list renames the Set*PushConstants to Push*Constants to match their push descriptor counterparts, which are all named Push*. This change list also contains a change for PushDescriptors.cpp that was accidentally left out of pr#237.
- Renamed SetGraphicsPushConstants to PushGraphicsConstants
- Renamed SetComputePushConstants to PushComputeConstants
- Removed API check for sample 26 since it's a Vulkan only sample.
> Rename push constants functions

- benchmarks/graphics_pipeline/main.cpp
- Unlike "First Person Shooter" games where pressing W doesn't let you move off the ground (it stays at y=0), this implementation 
let you move off the ground (y != 0).
> Adds Mouse free-fly camera controls

- src/test/log_console_test.cpp
The `LogInitialized` does not use the `LogTest` class, so the fix in
https://github.com/google/bigwheels/pull/243 did not apply there. This
applies the same fix for `LogInitialized`.
> Shutdown logging in the LogInitialized test

- include/ppx/application.h
- include/ppx/xr_component.h
Useful for mocking during unit tests, for making sure that passthrough was changed by the code under test.
> Add virtual to passthrough related methods.

- include/ppx/command_line_parser.h
- include/ppx/string_util.h
- src/ppx/application.cpp
- src/ppx/command_line_parser.cpp
- src/ppx/string_util.cpp
- src/test/command_line_parser_test.cpp
- src/test/string_util_test.cpp
* Changed CliOptions implementation to remove extra options. All options are stored as key (string) and value (list of strings) pairs in an unordered map.
* Some validation has been removed at the parsing stage (e.g. `--gpu -3` will parse without error, but run into a different error later)
* Added some `string_util` helpers for parsing
Expanded commandline flags syntax to allow:
* Resolution flags : `--flag-name NxM`
* no- prefix for boolean flags : `--no-flag-name`
* Other boolean values accepted
* = between flag and value : `--flag-name=parameter`
> Adding more flexible specifications for commandline parsing

- include/ppx/knob.h
- include/ppx/string_util.h
- src/ppx/knob.cpp
- src/ppx/string_util.cpp
- src/test/knob_test.cpp
- src/test/string_util_test.cpp
Preparing knobs and utilities for implementing `StandardOptions` as knobs
To support vector knobs
* `GetExtraOptionValueOrDefault` in knob code replaced with `GetOptionValueOrDefault`
* Adding some unit test cases for complex knobs
Logging fixes/changes
* Changing `Application-Specific Flags` title into `Flags`
* Fix bug for `string_util::WrapText()` which would line break too early, added unit test case to catch this
* Added `Knob::ValueString()` and logging for initial knob values inside `UpdateFromFlags`, for easier debugging 
* Added `string_util::ToString()` util for drawing values of knobs
> Bug fixes, helper functions and better logging for string_util and knobs

- projects/fishtornado_xr/FishTornado.cpp
- projects/fishtornado_xr/FishTornado.h
This change updates FishTornado to use the proper bigwheels metrics systems now in place. This means when metrics are enabled using the --enable-metrics flag, fishtornado will add its own metrics in addition to the default ones provided by the application layer.
This also means the --ft-enable-metrics flag has been removed.
> Update FishTornado to use BW metrics

- assets/benchmarks/shaders/Benchmark_PsAluBound.hlsl
- assets/benchmarks/shaders/Benchmark_PsMemBound.hlsl
- assets/benchmarks/shaders/Benchmark_PsSimple.hlsl
- benchmarks/graphics_pipeline/main.cpp
- An alpha value of 0.5 is set to facilitate whether alpha blending is on or off.
- The textures and samplers (Albedo, Normal and MetalR) will be added in an upcoming PR.
> Add Vertex/Pixel shader knobs + output 0.5 alpha for all PS

- projects/08_basic_geometry/CMakeLists.txt
- projects/08_basic_geometry/main.cpp
Addressing 2 issues following: https://github.com/google/bigwheels/pull/252
1) Updating the shader dependency for the new shader that is being used
2) Allocating the right number size for the descriptor pool, since the number of entities has increased
> Fix 08_basic_geometry

- src/ppx/application.cpp
This knob happened to be removed as part of https://github.com/google/bigwheels/pull/260. Adding it back, so that we can fully use the metrics feature again.
> Add back the `--metrics-filename` knob.

- build.gradle
- projects/01_triangle/build.gradle
- projects/04_cube/build.gradle
- projects/04_cube_xr/build.gradle
- projects/08_basic_geometry/build.gradle
- projects/15_basic_material/build.gradle
- projects/16_gbuffer/build.gradle
- projects/fishtornado/build.gradle
- projects/fishtornado_xr/build.gradle
Previously copyTask would run before shaders are actually generated, so they wouldn't be included correctly on the first try after a clean build.
This changes a few things:
- copyTask must now run after the native build that generates shaders, and before generate assets task
- subprojects specify a list of assets, and a task defined at the root build.gradle copies them
- the shaders are copied into a build folder, instead of a new assets folder in a subproject
> Fix gradle isssue with packaging generated shaders

- include/ppx/application.h
- include/ppx/command_line_parser.h
- src/ppx/application.cpp
- src/ppx/command_line_parser.cpp
- src/test/command_line_parser_test.cpp
Add flag --config-json-path to accept commandline flags that are specified in a JSON file. This flag can be used multiple times. The priority of any conflicting flags is as follows:
later flag on commandline > earlier flag on commandline > flag in later JSON file > flag in earlier JSON file
For flags that accept multiple values, the same priority is used and only flags specified in the same JSON file or flags all on the commandline will be combined.
Detailed changes:
* Changed map `mAllOptions` to hold `strings` instead of `string_views` since there are now temporary strings originating from the JSON structure, changed some input parameters for `CliOptions` member functions to match.
* Created some `CommandLineParser` methods to aid in parsing options (these are public for unit testing …
> Add --config-json-path to accept flags specified in a JSON file.

- assets/benchmarks/shaders/Benchmark_VsAluBound.hlsl
- assets/benchmarks/shaders/Benchmark_VsSimple.hlsl
- The type of POSITION (float4) in the vertex shader input signature has
been modified, as it didn't correspond with the type of POSITION
(float3) in the vertex binding.
>  Adjust the vertex shader input signature to match the vertex binding

- CMakeLists.txt
- CONTRIBUTING.md
- README.md
- build.gradle
- include/ppx/application.h
- include/ppx/command_line_parser.h
- include/ppx/window.h
- include/ppx/xr_component.h
- src/ppx/application.cpp
- src/ppx/grfx/vk/vk_device.cpp
- src/ppx/xr_component.cpp
C++20 is not well support with all our compilation environments.
> Change C++ standard to C++17.

- assets/benchmarks/shaders/Benchmark_RandomNoise.hlsl
- assets/benchmarks/shaders/CMakeLists.txt
- benchmarks/graphics_pipeline/CMakeLists.txt
- benchmarks/graphics_pipeline/main.cpp
Adding knob for rendering N fullscreen random quads to graphics_pipeline benchmark
Added
* Pseudo random noise shader
* Slider knob for adjusting number of quads
* `Entity2D` structure for holding info related to noise quads
> Adding knob for rendering N fullscreen random quads 

- benchmarks/graphics_pipeline/main.cpp
* First renderpass for sphere scene
* [optional] N renderpasses for N noise quads
* [optional] Last renderpass for` ImGui`
* Also moved end timestamp so that it does not include imgui rendering
> Split rendering in graphics_pipeline into separate renderpasses 

- benchmarks/graphics_pipeline/main.cpp
- projects/28_gltf/main.cpp
- src/CMakeLists.txt
- src/ppx/single_header_libs_impl.cpp
- src/ppx/tri_mesh.cpp
- Updated cgltf to latest master
- Moved cgltf implemenetation #include/#define to BigWheels core
- Moved tinyobj implementation #include/#define to common location
- Fixed casting warnings in 28_gltf
> cgltf maintenance for future work

- include/ppx/application.h
- src/ppx/window_android.cpp
Convert touch events to mouse movement:
- First touch will issue left mouse button press
- While the first touch is active it will be tracked as a mouse movement with left button pressed
- Other touches will not be registered
- When the first registered touch is lifted, the tracking will stop, until all touch points have lifted and a new "primary" touch is being tracked
> Emulate some mouse movement/press with touch on Android

- include/ppx/application.h
This is useful for mocking during unit tests, and verifying that metrics are added as requested.
> Add virtual to metrics related methods.

- include/ppx/grfx/dx12/dx12_command.h
- include/ppx/grfx/grfx_command.h
- include/ppx/grfx/grfx_config.h
- include/ppx/grfx/grfx_enums.h
- include/ppx/grfx/grfx_image.h
- include/ppx/grfx/grfx_render_pass.h
- include/ppx/grfx/vk/vk_command.h
- projects/04_cube/Cube.cpp
- projects/04_cube/Cube.h
- src/ppx/grfx/dx12/dx12_command.cpp
- src/ppx/grfx/grfx_command.cpp
- src/ppx/grfx/grfx_render_pass.cpp
- src/ppx/grfx/vk/vk_command.cpp
This CL adds missing clear functions for render targets and depth stencils that clear images within a render pass.
- Added clear functions for render targets and depth stencil.
- Added depth/stencil clear flag enum bits.
- Added functions to expose mip level and array layer in RTV and DSV.
- Added logic to determine if grfx::RenderPass contains any attachments with clear ops.
- Changed clear count check in grfx::CommandBuffer::BeingRenderPass to only check if there's a clear attachment.
- Added function to grfx::RenderPass to return index of an image.
- Added clear function implementation to Vulkan and D3D12.
- Modified 04_cube to use clear functions.
> Graphics clear funtions

- include/ppx/xr_component.h
- include/ppx/xr_composition_layers.h
- src/CMakeLists.txt
- src/ppx/xr_component.cpp
- src/ppx/xr_composition_layers.cpp
This allows XR projects, such as FishTornado XR, to add additional OpenXR layers as needed. This could be useful for rendering additional information in a new quad, or drawing multiple projections (such as additional cubes in 04_cube_xr).
Additional layers will be created by the project, moved into XrComponent, and optionally removed later via a reference id.
> Add ability to add additional OpenXR layers.

- projects/fluid_simulation/main.cpp
- projects/fluid_simulation/shaders.h
- projects/fluid_simulation/sim.h
We are not really using doxygen for anything and it doesn't seem to work with github (which was my hope).  So, I give up.
This removes all the markers I had added to the source code.
> Remove doxygen markers from fluid simulation files - NFC

- projects/fluid_simulation/main.cpp
- projects/fluid_simulation/shaders.cpp
- projects/fluid_simulation/shaders.h
- projects/fluid_simulation/sim.cpp
- projects/fluid_simulation/sim.h
This is the first step to fix #299.  It moves the creation of the simulation instance into a static method and starts disentangling it from the application.
Further cleanups will remove the ppx::Application link and the command buffer creation.
> Re-factor simulation instance creation

- include/ppx/grfx/grfx_enums.h
- src/ppx/grfx/vk/vk_device.cpp
This CL fixes some issues with how Vulkan device extensions were being handled:
- Updated grfx::Api enum values to take concrete values to allow for version checking.
- Add VK_EXT_descriptor_indexing features.
- Updated loading / feature handling for timeline host query reset and timeline semaphores.
- Removed VK_KHR_dynamic_rendering loading since it's not used anywhere. Will add it back when full support for dynamic rendering gets added.
> Updates to Vulkan device extension handling

- include/ppx/grfx/grfx_swapchain.h
- src/ppx/grfx/dx12/dx12_swapchain.cpp
- src/ppx/grfx/grfx_swapchain.cpp
Instead of creating them in a RenderPass.
This is in preparation for dynamic rendering where we still need to get RTVs and DSVs but do not need a render pass.
> Explicitly create RTVs and DSVs in Swapchain

- src/ppx/application.cpp
This scoped timer usage was invalid. Not giving a variable name means this get destroyed in the same statement it's created, not at the end of the scope.
> app: fix scoped timer usage

- assets/common/shaders/ppx/Math.hlsli
- assets/common/shaders/ppx/PBR.hlsli
- Replaced CartesianToSpherical with obstensibly more efficient DirectionToLatLongUV
> More efficient SampleIBLTexture()

- include/ppx/geometry.h
- src/ppx/geometry.cpp
The initial resize policy for the buffer was "minimalist". Only resized to match the added element.
Changed this policy to be "double the size". Every time we reach the size limit, the underlying container size is doubled.
This reduces the benchmark loading time from 30s to 15s in debug. (367M resize calls to 725).
> geometry: change resize policy to be double

- benchmarks/graphics_pipeline/build.gradle
- settings.gradle
- Even though the benchmark app does not run on Android devices that don't support the `push_descriptor` extension, this is the first step.
> Set up the Benchmark app for Android

- benchmarks/graphics_pipeline/GraphicsBenchmarkApp.cpp
- benchmarks/graphics_pipeline/GraphicsBenchmarkApp.h
Fullscreen quads
* Adding knob for toggling if they are rendered on a single renderpass or on separate ones
* Changing the vertex data to create one large triangle instead of two smaller ones, to avoid different behaviour for the shading of pixels on the diagonal
`Render()`
* Some refactoring of the following logic for clarity:
* Command buffer recording
> Some changes for graphics_pipeline fullscreen quads, and Render()

- benchmarks/graphics_pipeline/GraphicsBenchmarkApp.cpp
- benchmarks/graphics_pipeline/GraphicsBenchmarkApp.h
Need to generate project with 
```
cmake -B build -G "Visual Studio 16 2019" -A x64 -DPPX_BUILD_XR=1
```
Then change `settings.xr.enable` to `true` to enable XR mode 
The benchmark xr version is done within the original project (instead of duplicating the project and have a `xr` version like fishtornado and cube) because the benchmark itself is WIP, and this could avoid duplicating the changes in 2 projects. 
The downside is that there is a lot of `#if defined(PPX_BUILD_XR)` in the .h/.cpp files (this was the main reason why the cube_xr and fishtornado_xr were in separate projects)
I will do another pass in a separate PR to move all #if defined(PPX_BUILD_XR) into the base class or framework so that we don't do this ifdefs in the application.
> Add XR support to benchmark

- benchmarks/graphics_pipeline/GraphicsBenchmarkApp.cpp
- benchmarks/graphics_pipeline/GraphicsBenchmarkApp.h
- include/ppx/grfx/grfx_command.h
- include/ppx/grfx/grfx_descriptor.h
- src/ppx/grfx/vk/vk_descriptor.cpp
* Replace push descriptors with traditional descriptors
* Rename variables with `Skybox` -> `SkyBox` for consistency
* Some comment/spacing corrections for bigwheels (not functional)
* Minor adjustments to knob appearance in UI (indent, ordering)
> Remove use of push descriptor extension from graphics_pipeline benchmark

- benchmarks/graphics_pipeline/SphereMesh.cpp
- include/ppx/tri_mesh.h
This allows the low precision vertex data to work on DX12. DX12 does not have an equivalent to FORMAT_R16G16B16_FLOAT, but it does have an equivalent to FORMAT_R16G16B16A16_FLOAT.
Tested on DX12 and Vulkan (Windows OS with Quadro P1000).
> Changed format of low precision vertex data.

- benchmarks/graphics_pipeline/GraphicsBenchmarkApp.cpp
- benchmarks/graphics_pipeline/GraphicsBenchmarkApp.h
Usage example:
vk_graphics_pipeline.exe --fullscreen-quads-texture-path benchmarks/textures/bricks_1080p.png
> Add startup only flag for texture path for fullscreen quad

- .github/workflows/linux-build.yml
- cmake/ShaderCompile.cmake
- src/ppx/grfx/grfx_descriptor.cpp
- src/ppx/grfx/vk/vk_descriptor.cpp
- src/ppx/grfx/vk/vk_device.cpp
In order to fully support resource arrays, also require and enable shader*ArrayDynamicIndexing device features.
This allows one to use push constants to select texture within an array of textures like in 24_push_constants
Does not add support for using push descriptors with arrays.
Dynamic indexing features are not required for just using shader resource arrays with constant indices.
Currently, from what I can tell, only 24_push_constants requires enabling shaderSampledImageArrayDynamicIndexing and there are some small number of gpus that don't support those features (software lavapipe).
We could handle this in a few different ways:
1) Enable dynamic indexing features across the board, fail on the devices that don't support them. This would mean that BigWheels won't run on some devices …
> Use vulkan descriptor arrays instead of flattening them

- benchmarks/graphics_pipeline/GraphicsBenchmarkApp.cpp
- src/ppx/application.cpp
- src/ppx/knob.cpp
- src/test/knob_test.cpp
Add default value of the knob to the usage message as `(Default: <value>)` for standard knobs and graphics_pipeline
Also cleaned up usage messages
- remove defaults written in message
- standardize syntax for referring to other flags like `--other-flag`
- did not touch flags `--assets-path`, `--metrics-filename`, `--screenshot-path` as those will be changed in follow up PRs
- minor changes to description for some other knobs
> Add default value of knob to the usage message

- include/ppx/application.h
Otherwise this triggers an error of
"no viable conversion from 'basic_string<char8_t>' to 'basic_string<char>'"
> Call string() instead of u8string() for default metrics filepath

- include/ppx/application.h
- src/ppx/application.cpp
For sliders, currently the max values are being used rather than the default values.
Also changing some `int` -> `uint32_t` since those flags cannot be negative
> Fix standard knob default values for sliders

- include/ppx/knob.h
- projects/fluid_simulation/main.cpp
- src/ppx/application.cpp
- src/test/knob_test.cpp
Preferred for the shorter syntax, and it suits the usual split between knob declaration in header file and initialization in the cpp.
> Refactor knob creation to use InitKnob

- benchmarks/graphics_pipeline/GraphicsBenchmarkApp.cpp
- benchmarks/graphics_pipeline/GraphicsBenchmarkApp.h
- It considerably reduces the startup time and memory by initializing only 100 spheres.
> Benchmark: Initialize spheres on demand 

- benchmarks/graphics_pipeline/GraphicsBenchmarkApp.cpp
The time computation for multi-pass rendering was incorrect. For both `Timestamp Queries` to the GPU, the PIPELINE_STAGE_TOP_OF_PIPE_BIT stage was erroneously used. To correct this, the first timestamp should use the PIPELINE_STAGE_TOP_BIT stage to record the timestamp as soon as all previous commands are processed by the command processor. The second timestamp should employ the PIPELINE_STAGE_BOTTOM_BIT stage to record the timestamp as soon as all previous commands retire.
> Fix invalid timestamp computation for single-pass rendering

- .github/workflows/linux-build.yml
- .github/workflows/windows-build.yml
- include/ppx/application.h
- include/ppx/fs.h
- include/ppx/metrics.h
- src/ppx/application.cpp
- src/ppx/fs.cpp
- src/ppx/metrics.cpp
- src/ppx/ppm_export.cpp
- src/test/CMakeLists.txt
- src/test/filesystem_util_test.cpp
- src/test/metrics_test.cpp
and the behavior of associated flags `--screenshot-path` and `--metrics-filename` to make them more consistent with each other.
> Changes to metrics report and screenshot filenames

- projects/29_dynamic_rendering/CMakeLists.txt
It was removed everywhere else in https://github.com/google/bigwheels/pull/374
> Remove cmake_minimum_required from dynamic rendering sample

- .github/workflows/android-build.yml
- .github/workflows/linux-build.yml
- .github/workflows/windows-build.yml
- benchmarks/graphics_pipeline/GraphicsBenchmarkApp.cpp
- include/ppx/application.h
default to debug for debug non-android builds
add graphics pipeline to github CI builds since it is under active development.
> Add validation to github CI and upgrade vulkan sdk to latest

- include/ppx/imgui_impl.h
- include/ppx/xr_component.h
- src/ppx/application.cpp
- src/ppx/imgui_impl.cpp
- src/ppx/xr_component.cpp
Simulate a mouse using right controller.
Uses "Khronos Simple Controller Profile", which should be available on most devices.
Controller input is interpreted as follows:
- `/user/hand/right/input/select/click` as left button 
- `/user/hand/right/input/aim/pose` as cursor using ray cast
> XR simulated mouse input

- include/ppx/grfx/vk/vk_device.h
- src/ppx/grfx/vk/vk_device.cpp
This changes the logic for activating the shading rate extensions (VK_KHR_fragment_shading_rate, VK_EXT_fragment_density_map). Previously both extensions were activated whenever they were available, now only the extension corresponding to the requested shading rate mode is activated.
We already only enable the *feature* for one of the shading rate modes (to avoid a validation error), so this change just avoids adding unused extensions.
> Only activate extensions for selected shading rate mode.

- src/ppx/grfx/vk/vk_device.cpp
This typo slipped by in the previous PR due to my testing the wrong APK. Apologies for the churn.
> Fix typo in enabling VRS extension.

- projects/fluid_simulation/shaders.cpp
- projects/fluid_simulation/sim.cpp
- projects/fluid_simulation/sim.h
**NOTE TO REVIEWERS: This is a very simple change but relies on the new code structure from #323, #396 and #397.  Please review those first. Thanks.**
This adds a call back for `Resize` so that the simulation grids can be re-allocated to match the new window size.
Fixes #229.
> Make fluid simulation window re-sizable

- assets/fluid_simulation/shaders/advection.hlsl
- assets/fluid_simulation/shaders/config.hlsli
- assets/fluid_simulation/shaders/display.hlsl
- projects/fluid_simulation/shaders.h
- projects/fluid_simulation/sim.cpp
- projects/fluid_simulation/sim.h
**NOTE TO REVIEWERS: This relies on the new code structure from #323, #396, #397 and #398. Please review those first. Thanks.**
This fixes #226.
Some options were dynamic in the C++ code, but were a static #define in the HLSL code.  This makes all these fitlering options a dynamic setting.
> Add dynamic filtering

- projects/fluid_simulation/README.md
- projects/fluid_simulation/main.cpp
- projects/fluid_simulation/shaders.cpp
- projects/fluid_simulation/shaders.h
- projects/fluid_simulation/sim.cpp
- projects/fluid_simulation/sim.h
This renames pointer variables to use the `pNAME` convention (from https://github.com/google/bigwheels/pull/396#discussion_r1447951887).
Additional minor NFC fixes:
- Fix IWYU issues in files.
- Document new knobs in `README.md`.
- Fix documentation for `GetNormalizedSize()` (#400)
> Fix names for pointer variables and arguments

- projects/fluid_simulation/README.md
- projects/fluid_simulation/sim.cpp
- projects/fluid_simulation/sim.h
This adds a new knob to enable/disable the rendering of the intermediate grids using during simulation.  This used to be enabled by `--enable-debug`, but this makes it easier to split API verification from showing these grids.
> Add new knob to display CFD grids

- include/ppx/application.h
It is used for internal tests to mock the GetXrComponent function
> Add back virtual to GetXrComponent

- benchmarks/graphics_pipeline/GraphicsBenchmarkApp.cpp
- src/ppx/grfx/vk/vk_device.cpp
Fixes:
- #432 Adding WaitIdle() before sphere descriptors are updated
- #423 Setting fillModeNonSolid to true for all applications to allow use of VK_POLYGON_MODE_LINE
> Fixes for graphics_pipeline benchmark wireframe mode and 1x1 texture mode

- docs/building_and_running.md
These packages are required to run the build instructions in the doc.
> docs: Add cmake and ninja-build to Linux packages

- include/ppx/grfx/vk/vk_device.h
- src/ppx/grfx/vk/vk_device.cpp
- src/ppx/grfx/vk/vk_instance.cpp
- src/ppx/grfx/vk/vk_pipeline.cpp
* VUID-VkShaderModuleCreateInfo-pCode-08742 : Needs to be checked by messageIdName and not messageIdNumber
* VUID-VkPipelineRasterizationStateCreateInfo-pNext-pNext : Need extension VK_EXT_depth_clip_enable rather than VK_EXT_depth_range_unrestricted
> Fixes for Vulkan Validation errors

- include/ppx/grfx/dx12/dx12_device.h
- include/ppx/grfx/grfx_descriptor.h
- include/ppx/grfx/grfx_device.h
- include/ppx/grfx/grfx_helper.h
- include/ppx/grfx/vk/vk_descriptor.h
- include/ppx/grfx/vk/vk_device.h
- include/ppx/grfx/vk/vk_util.h
- src/ppx/grfx/dx12/dx12_descriptor.cpp
- src/ppx/grfx/dx12/dx12_device.cpp
- src/ppx/grfx/vk/vk_descriptor.cpp
- src/ppx/grfx/vk/vk_device.cpp
- src/ppx/grfx/vk/vk_util.cpp
DX12 support may be added later. Adds supports for partially bound descriptors, which allows us to create arrays for textures where only a subset of the allotted slots are used.
> Add support for partial bindings (vk only)

- src/ppx/camera.cpp
I added an ArcballCamera to #428 and noticed that it wasn't working as expected.
ArcballCamera wasn't updating `mViewProjectionMatrix` after modifying `mViewMatrix`. This was causing the ArcballCamera to not work correctly when combined with the classes introduced in #426.
> Update mViewProjectionMatrix in ArcballCamera::UpdateCamera

- benchmarks/graphics_pipeline/GraphicsBenchmarkApp.cpp
When compiled with C++20, the operator != is ambiguous in this case
> Use the IsNull method on ObjPtr instead of operator !=

- projects/timeline_semaphore/CMakeLists.txt
- src/ppx/platform.cpp
- Add "Android" platform name
- Remove the cmake version line from timeline_semaphore it was a relatively new project
> Small fixes: platform name, cmake warning

- include/ppx/grfx/grfx_swapchain.h
- src/ppx/grfx/grfx_swapchain.cpp
We create convenience render passes that write to swapchain images. One set with LOAD_OP_CLEAR and one with LOAD_OP_LOAD. Previously LOAD_OP_LOAD render passes used LOAD_OP_CLEAR for depth stencil attachment, now we will use LOAD_OP_LOAD.
Tested by modifying dynamic rendering sample to use regular render passes.
Fixes https://github.com/google/bigwheels/issues/467
> Use LOAD_OP_LOAD for DSV in swapchain load render pass

- src/android/main.cpp
- src/ppx/window_android.cpp
This commit is sourced from a downstream patch.
The incoming NDK r27 removes `ALooper_pollAll` as it can't be called safely.
See https://github.com/android/ndk/discussions/2020 for more context.
While this change strives to introduce as little behavior change as possible, Some behavior changes might be happening.
1. We are failing more explicitly when `ALooper_pollOnce` returns `ALOOPER_POLL_ERROR`. When this error is returned, there is no point in retrying polling in the current thread.
2. Compared with `ALooper_pollAll`, `ALooper_pollOnce` can return more frequently with `ALOOPER_POLL_CALLBACK`. This can lead to "on_idle" logic being executed more frequently.
> Replace ALooper_pollAll with ALooper_pollOnce

- include/ppx/scene/scene_gltf_loader.h
- include/ppx/scene/scene_loader.h
- include/ppx/scene/scene_mesh.h
- src/CMakeLists.txt
- src/ppx/scene/scene_gltf_loader.cpp
Using the library `cgltf`, implements a GLTF scene laoder for BigWheels's scene graph.
Also, defines an interface for generic scene loaders, in case we come up with other ways of storing and loading scenes.
> Add GLTF Scene Loader

- benchmarks/graphics_pipeline/GraphicsBenchmarkApp.cpp
- include/ppx/application.h
- projects/cube_xr/CubeXr.cpp
- projects/fishtornado_xr/FishTornado.cpp
- src/ppx/application.cpp
Remove debug capture option, tools like RenderDoc can capture directly, and it makes code more complicated.
Also use IsXrEnabled instead of settings.xr.enable, that way we can switch how that is controled in the function.
Fixes https://github.com/google/bigwheels/issues/464
> Remove debug capture setting

- include/ppx/grfx/grfx_shading_rate_util.h
- src/CMakeLists.txt
- src/ppx/grfx/grfx_shading_rate_util.cpp
The first of a series of CL that integrates the commits from:
https://github.com/bjoeris/bigwheels/tree/experimental-foveation
into BW main's branch. 
The series will have 4 CL, this is the first ona that integrates the following commit
* Add util functions to fill foveation pattern bitmaps
> Add util functions to fill foveation pattern bitmaps

- include/ppx/grfx/dx12/dx12_device.h
- include/ppx/grfx/grfx_device.h
- include/ppx/grfx/vk/vk_device.h
- src/ppx/grfx/dx12/dx12_device.cpp
- src/ppx/grfx/vk/vk_device.cpp
For Vulkan, we must ask for the VK_EXT_index_type_uint8 device extension and enable the indexTypeUint8 feature.
For DX12, the docs claim that there is no support: https://learn.microsoft.com/en-us/windows/win32/direct3ddxgi/hardware-support-for-direct3d-12-0-formats
This is required to load uint8 index buffers from glTF files more efficiently. See #453
> Declare support for UINT8 index buffer

- README.md
- docs/code_coverage.md
I find code coverage metrics useful to identify missing tests. I only provided GCC instructions since that's the toolchain that I'm used to working with.
> Add instructions for generating code coverage

- src/ppx/imgui_impl.cpp
Updating ImGUI to v1.90.3.
Requires 2 small changes:
- removed not unnecessary calls to the FontsTexture functions.
- changed the setup for dynamic rendering.
> deps: update ImGUI to v1.90.3

- cmake/ShaderCompile.cmake
Fix the cmake rule to build GLSL shaders on Android
I tested doing a local build on a Windows desktop using Android Studio
> Fix GLSL shader build rule in Android

- include/ppx/grfx/grfx_image.h
- include/ppx/grfx/grfx_shading_rate.h
- include/ppx/grfx/vk/vk_shading_rate.h
- src/ppx/grfx/grfx_image.cpp
- src/ppx/grfx/grfx_render_pass.cpp
- src/ppx/grfx/vk/vk_device.cpp
- src/ppx/grfx/vk/vk_render_pass.cpp
- src/ppx/grfx/vk/vk_shading_rate.cpp
- src/test/vk_shading_rate_test.cpp
The fourth of a series of CL that integrates the commits from:
https://github.com/bjoeris/bigwheels/tree/experimental-foveation
into BW main's branch.
The series has 4 CL, this is the last one that integrates the following commit
* Add multisample support for ShadingRatePattern.
Beside the foveation sample app, it also adds the following changes in BW infra:
* ShadingRate’s class add sample count properties, that queries from device
* Modifies gfx View classes to get the sample count from images
* Image class get samples count from createinfo struct
* ShadingRates unit test get modified to account for this changes
> Add multisample support for ShadingRatePattern.

- include/ppx/grfx/grfx_util.h
- src/ppx/geometry.cpp
- src/ppx/grfx/grfx_util.cpp
- src/test/CMakeLists.txt
- src/test/geometry_test.cpp
Unlike `AppendIndex` and friends, `AppendIndicesU32` doesn't account for `INDEX_TYPE_UNDEFINED`. Consider:
```c++
Geometry geometry;
Geometry::Create(GeometryCreateInfo{}.IndexType(grfx::INDEX_TYPE_UNDEFINED).AddPosition(), &geometry);
std::array<uint32_t, 3> data = {0, 1, 2)
geometry.AppendIndicesU32(data.size(), data.data());
EXPECT_EQ(geometry.GetIndexBuffer()->GetSize(), 0);
```
This test would fail since the data would be written to the index buffer!
This seems like an oversight. The condition has been fixed and tests have been added.
> Require UINT32 type in Geometry::AppendIndicesU32

- src/test/geometry_test.cpp
The assertion text varies based on platform. Since I care more about the assertion rather than the contents of the assertion, it makes sense to leave the matcher generic.
Fixes #496
> Support more platforms in Geometry death test

- benchmarks/foveation/FoveationBenchmarkApp.cpp
- benchmarks/foveation/FoveationBenchmarkApp.h
Makes the foveation app able to use multisample foveation
This change was missing from the previous PR #493
> Add multisample to foveation app

- src/ppx/grfx/vk/vk_swapchain.cpp
We are currently not set up to render to multisampled images in BigWheels.
> Always set sampleCount to 1 for XR swapchain

- src/ppx/grfx/vk/vk_device.cpp
- src/ppx/grfx/vk/vk_util.cpp
When the graphics queue was distinct from the compute queue, access & stage bits could be incorrectly computed. This was caused by the command type not being linked to each queue, and some invalid condition in an utility function designed to derive access & stage bits from an access type.
Tested on my local machine, all sampled except one (push_descriptor) passes. This failure already exists on main.
> vk: fix sync masks for split compute/graphics.

- src/test/geometry_test.cpp
In order to add uint8 index buffer support to Geometry, I need to touch many functions. To ensure that these functions continue to work, I would like to add some unit tests.
> Add Geometry unit tests for index buffer functions

- include/ppx/geometry.h
- include/ppx/grfx/grfx_enums.h
- src/ppx/geometry.cpp
- src/ppx/grfx/grfx_util.cpp
- src/ppx/grfx/vk/vk_util.cpp
- src/ppx/tri_mesh.cpp
- src/ppx/wire_mesh.cpp
- src/test/geometry_test.cpp
Add support for creating buffers that the GPU can accept if IndexTypeUint8Supported(). The client must decide which index type to use depending on the supported features of the API and GPU; it is possible to create a Uint8 buffer which i.e. is not accepted by DX12.
This is required for #453
> Add UINT8 index buffer support to Geometry

- src/ppx/geometry.cpp
Calling GetElementCount for index type UNDEFINED is an odd corner case that exposed a division by 0. If the mElementSize is 0 then we can't meaningfully calculate the element count so return 0.
> Avoid division by 0

- benchmarks/graphics_pipeline/GraphicsBenchmarkApp.cpp
For the Quad render.
Uniforms (constant) were only passed correctly in the case of type noise.
> Fix incorrect uniforms passing

- src/ppx/scene/scene_gltf_loader.cpp
While reviewing scene_gltf_loader.cpp, I found some functions that weren't being used. These have been removed.
> Remove dead code from scene_gltf_loader.cpp

- src/ppx/scene/scene_gltf_loader.cpp
The unlit material extension name is unused. This is probably because cgltf already looks for this extension and exposes it as `cgltf_material::unlit`; we don't need to look for the extension ourselves.
> Remove unused GLTF materials define

- src/ppx/scene/scene_gltf_loader.cpp
`cgltf_data*` is never meaningfully used inside the function body. It can be removed.
> Remove unused parameter from GetStartAddress

- include/ppx/grfx/grfx_enums.h
- include/ppx/grfx/grfx_helper.h
- src/ppx/grfx/grfx_helper.cpp
Default enum value was not a valid enum value, which caused issue with asan. This fixed unit tests with this sanitizer enabled.
> fix sanitize-enum finding

- projects/gltf_basic_materials/GltfBasicMaterials.cpp
- projects/gltf_basic_materials/GltfBasicMaterials.h
Introduce a KnobFlag for specifying which GLTF scene to load. This is relative to the asset path. This allows us to load additional scenes without recompiling.
> Add GLTF asset option to gltf_basic_materials

- include/ppx/grfx/vk/vk_shading_rate.h
Otherwise with certain flags it fails to build because of ToApi() function convertiong vk::Device to Device as it does not know that vk::Device inherits from Device.
> Include additional header

- projects/gltf_basic_materials/GltfBasicMaterials.cpp
- projects/gltf_basic_materials/GltfBasicMaterials.h
Allow loading scenes without a camera. If there is no camera then provide one that the user can interact with. As someone validating GLTF support, I find this preferable to a static camera so that I can look at the scene from any angle at runtime.
Fixes #456
> Provide a camera if there's none in the scene

- src/ppx/grfx/vk/vk_device.cpp
Commit 95179ed72654f672dc0680fdb3465f16af5ec036 changed the way queue count were set, meaning we only created queues on demand. This causes validation issues as it is not legal to set the requested queue count to zero when requesting queues.
See: VUID-VkDeviceQueueCreateInfo-queueCount-arraylength
> grfx, vk: fix queueCount being zero

- CMakeLists.txt
This warning seems to only impact clang.
> build: fix warning in upstream GLI

- .github/workflows/android-build.yml
- .github/workflows/check-formatting.yml
- .github/workflows/linux-build.yml
Ubuntu 20.04 has been removed as a runner, causing checks to fail on PRs.
Ubuntu 24.04 was chosen in the hopes that we won't have to think about it for a few more years than if we were to choose Ubuntu 22.04.
This required additional changes:
- Linux build requires `convert` so make sure imagemagick is installed.
- clang-format was pinned to `clang-format-12` but this package is not in 24.04. The oldest version that 24.04 offers is `clang-format-14`. I'm worried about pushing this too high, having it change how it wants code formatted, and creating churn for PR authors. Though maybe I'm overthinking this.
Fixes #555
> Upgrade Linux job runner to Ubuntu 24.04

- projects/gltf_basic_materials/CMakeLists.txt
1. CMake 4.0 stopped supporting CMake 3.5: https://cmake.org/cmake/help/latest/release/4.0.html#deprecated-and-removed-features
2. Remains consistent with other projects. See 11aa8fb18a18d8c39bc688e66a305dfc2c8b0398
3. As mentioned in 11aa8fb18a18d8c39bc688e66a305dfc2c8b0398, the subdirectories are not standalone so ought to inherit the minimum requirements from the parent.
> Remove cmake_minimum_required from gltf_basic_materials

- .github/workflows/check-formatting.yml
clang-format-check uses DoozyX/clang-format-lint-action, which provides their own clang-format binaries. So the explicit clang-format install is not needed. Additionally, it's confusing that we install 14 but DoozyX/clang-format-lint-action uses 16
> Remove unused clang-format install in workflow

- src/ppx/grfx/vk/vk_device.cpp
While not a complete fix for #484, now on Pixel 6a I get the more helpful error message:
```
*** PPX ASSERT ***
Message   : Device does not support required features: fillModeNonSolid
Condition : false
Function  : ConfigureFeatures
Location  : /usr/local/google/home/hitchens/git/bigwheels/src/ppx/grfx/vk/vk_device.cpp : 326
```
> Check for more Vulkan features

- include/ppx/application.h
- include/ppx/xr_component.h
- projects/cube_xr/CMakeLists.txt
- projects/cube_xr/CubeXr.cpp
- projects/cube_xr/CubeXr.h
- src/ppx/application.cpp
- src/ppx/xr_component.cpp
Adds multiview into Cube_XR. This is a followup to pr#419 where multiview was added to the repo.
> Adds multiview to CubeXr

- .github/workflows/android-build.yml
- build.gradle
- projects/cube_xr/CubeXr.cpp
The template inference fails on 32bit builds because of sizeof. Making the templated type explicit solves this.
> cubexr: fix 32bit build

- include/ppx/obj_ptr.h
This adds no value. If required in the future, it can be retrieved from git history
> Remove commented code in obj_ptr.h

- include/ppx/obj_ptr.h
Tell the compiler that `ObjPtr<T>::operator&` can only be called on lvalues (not temporaries). This would have prevented #565 from compiling:
```
/usr/local/google/home/hitchens/git/bigwheels/benchmarks/graphics_pipeline/GraphicsBenchmarkApp.cpp:1151:43: error: taking the address of a temporary object of type 'grfx::SemaphorePtr' (aka 'ObjPtr<Semaphore>') [-Waddress-of-temporary]
1151 |         submitInfo.ppSignalSemaphores   = &GetSwapchain()->GetPresentationReadySemaphore(imageIndex);
|                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/google/home/hitchens/git/bigwheels/benchmarks/graphics_pipeline/GraphicsBenchmarkApp.cpp:1151:43: error: incompatible pointer types assigning to 'grfx::Semaphore **' from 'grfx::SemaphorePtr *' …
```
> Prevent stack-use-after-scope with ref-qualifier

- .github/workflows/android-build.yml
- .github/workflows/linux-build.yml
- .github/workflows/windows-build.yml
Use the latest validation layers in CI to take advantage of the additional checks (e.g. https://github.com/google/bigwheels/issues/562)
> Update GitHub Actions to Vulkan 1.4.321.1
