google/bigwheels

include/ppx/xr_component.h, src/ppx/application.cpp
=> Only destroy XR component when enabled

include/ppx/application.h, include/ppx/xr_component.h, projects/04_cube_xr/main.cpp, projects/fishtornado_xr/FishTornado.cpp, projects/fishtornado_xr/FishTornado.h, src/ppx/application.cpp, src/ppx/xr_component.cpp
- using one extra composition layer Quad for the ImGui UI elements.
=> Adding ImGui Support

src/ppx/grfx/vk/vk_swapchain.cpp
Cleaned up a few comments and local variables too.
=> [OpenXR] Add depth swapchain support for Vulkan

assets/gbuffer/shaders/DeferredLight.hlsl, projects/16_gbuffer/main.cpp
- Updated gbuffer sample to use license compliant version of the PBR and related functions.
- Added intensity values to the constnat buffer since this version of the PBR function takes light intensity into account.
=> License compliant version of gbuffer's PBR code

projects/fluid_simulation/sim.h
This adds the comment that was requested in https://github.com/google/bigwheels/pull/20/commits/cb2459fc6ae90e0da1db0cfe61b7b9877a0d38ce#r1041343843 which I somehow lost.
=> Add comment that was lost in a re-base operation

projects/alloc/main.cpp
It was causing assertions in debug mode.
=> Fix alloc sample to use minimum buffer sizes to avoid assertions

projects/oit_demo/OITDemoApplication.cpp, projects/oit_demo/OITDemoApplication.h
I missed this during the review.
=> Do not update GUI if ImGui is disabled

include/ppx/application.h, src/ppx/application.cpp
Changed erroneously named `dx12` to `dx`
=> Fixed variable name

include/ppx/application.h, src/ppx/application.cpp, src/ppx/bitmap.cpp, src/ppx/csv_file_log.cpp, src/ppx/graphics_util.cpp
- Fixed cast warnings for some pointers and integers
- Moved multiline function(s) from header to source
- Renamed mSwapchain to mSwapchains since it can store more than one swapchain
- Fixed some styling issues (overall style guidance will be addressed later)
=> Fixed warnings and some style issues

include/ppx/xr_component.h, src/ppx/application.cpp
If a target resolution is specified via the `--resolution` command line flag, the value will be passed through to XrComponent.
=> Fix --resolution flag for XR devices.

include/ppx/application.h
This was missed from https://github.com/google/bigwheels/pull/149.
=> Remove GLFW from Android builds.

src/ppx/grfx/grfx_swapchain.cpp
This change removes some overly aggressive and incorrectly behaving asserts during swapchain depth image creation.
=> Swapchain XR fix

include/ppx/grfx/grfx_swapchain.h, include/ppx/grfx/vk/vk_swapchain.h, include/ppx/log.h, src/android/AndroidManifest.xml, src/ppx/application.cpp, src/ppx/grfx/vk/vk_swapchain.cpp, src/ppx/window_android.cpp
- Discard VK_SUBOPTIMAL_KHR error.
- Handling content rect changed events.
=> Android free rotation.

CONTRIBUTING.md, README.md
Give some info around review SLO, and how we distribute reviews around.
=> docs: add more details to the contribution guide

docs/building_and_running.md
To specify how to select different samples from Android Studio
=> Update building documentation

projects/04_cube_xr/CubeXr.h
This was missed from https://github.com/google/bigwheels/pull/173.
=> Add missing header guard.

docs/high-level-architecture.md
Added info about the knob framework in the docs next to where ImGui and GetExtraOptions are mentioned.
=> Update docs with info about the knob framework.

.github/workflows/android-build.yml, .github/workflows/linux-build.yml, .github/workflows/windows-build.yml
This PR adds a checksum check on linux workflows to check Vulkan SDK's integrity.
=> ci: add checksum check for vulkan SDK download

benchmarks/graphics_pipeline/main.cpp
- Also it was added a GPU work duration display.
=> Add a GPU FPS display

benchmarks/graphics_pipeline/main.cpp
- It allows to navigate into the scene where W = forward, S = backward, A = left and D = Right.
=> Add WASD functionality to keyboard

include/ppx/application.h, src/ppx/application.cpp
This change updates the application to automatically start metrics logging and produce a report if metrics are enabled (e.g. via the command line). This allows any application without specific metrics handling to get some baseline metrics information.
For more complicated use cases, classes derived from Application can override the SetupMetrics, ShutdownMetrics and UpdateMetrics methods to customize their behavior.
=> Update Application to include automatic metrics

benchmarks/graphics_pipeline/main.cpp
- This sphere will be used to instantiate up to 3000 spheres.
- The knobs to setup the longitudeSegments and latitudeSegments for
the spheres will be added in an upcoming PR.
=> Add a hard-coded sphere

CMakeLists.txt
cmake_path requires minimum 3.20
=> Update minimum CMake version.

benchmarks/graphics_pipeline/main.cpp
- It was added the textures for Albedo, NormalMap and metalness-roughness.
=>  Add textures for the pixel shaders

benchmarks/graphics_pipeline/main.cpp
- A giant vertex buffer is created to store all copies of the sphere mesh.
- The model matrix is applied at the vertex buffer level.
- The last draw call additionally renders all remaining spheres when the drawcall-count is not a divisor of the sphere-count.
*Ideally, the `maxValue` of the drawcall-count slider knob should be changed at runtime. Currently, the value of the drawcall-count is adjusted to the sphere-count in case the former exceeds the value of the sphere-count.
=> Add the drawcall-count knob to the core benchmark

benchmarks/graphics_pipeline/main.cpp, include/ppx/geometry.h, include/ppx/math_config.h, include/ppx/tri_mesh.h, src/ppx/geometry.cpp
- It was added a new Vertex Buffer that stores 16-bit floating point format for the vertex input including position, texCoord, normal and tangent.
=> Add knob for Vertex Buffer Format

benchmarks/graphics_pipeline/main.cpp, include/ppx/geometry.h, src/ppx/geometry.cpp
- It was added the VERTEX_ATTRIBUTE_LAYOUT_POSITION_PLANAR to the Vertex Attribute Layout.
=> Add the knob for Vertex Attribute Layout

include/ppx/string_util.h, include/ppx/transform.h, src/ppx/string_util.cpp, src/ppx/transform.cpp
This CL adds two general string utility functions and some changes to Transform that's needed by work on another branch.
- Added ToLowerCopy / ToUpperCopy to string_util.
- Added IsDirty() function to Transform.
- Virtualized some functions in Transform to allow easier inheritance.
=> Minor changes for future work

benchmarks/graphics_pipeline/GraphicsBenchmarkApp.cpp
* Correct clear/don't care renderpasses to fix glitch with disabled skybox configuration
* Remove unused variable rebuildPipeline
=> Fixes for graphics benchmark

benchmarks/graphics_pipeline/GraphicsBenchmarkApp.cpp, benchmarks/graphics_pipeline/GraphicsBenchmarkApp.h
- It also changes the visibility of knobs related to the spheres accordingly.
=> Enable/Disable the Spheres in the scene (Benchmark app)

benchmarks/graphics_pipeline/GraphicsBenchmarkApp.cpp, benchmarks/graphics_pipeline/GraphicsBenchmarkApp.h
- Don't resource leak pipelines when enable/disable depth/alpha.
- Sphere pipelines are now created on demand.
- Pipeline are cleaned up during shutdown.
=> Properly caching sphere pipelines.

benchmarks/graphics_pipeline/GraphicsBenchmarkApp.cpp, benchmarks/graphics_pipeline/GraphicsBenchmarkApp.h, benchmarks/graphics_pipeline/build.gradle, include/ppx/grfx/grfx_format.h, src/ppx/grfx/grfx_format.cpp
- Toggle between render directly to swapchain and offscreen buffer
- Toggle between blit result to swapchain and skip blit
- Enable non swapchain native image format
- Enable non swapchain compatible resolution
=> Benchmark: offscreen rendering.

docs/building_and_running.md
Make the prerequisites and build instructions more explicit for new contributors.
=> Update build and run docs

include/ppx/application.h, src/ppx/application.cpp
Minor refactoring: cleanup Application::Run()
=> Minor refactoring: cleanup Application::Run()

include/ppx/application.h, src/ppx/application.cpp
- Rename flag from `--assets-path` to `--extra-assets-path`
- Added warning for above
=> Combine functions related to adding asset dirs

.github/workflows/windows-build.yml
as the one for PPX_BUILD_XR=1 mentioned in
to work around https://github.com/google/bigwheels/issues/97
=> Add the same workaround for PPX_BUILD_XR=0

benchmarks/graphics_pipeline/GraphicsBenchmarkApp.cpp, benchmarks/graphics_pipeline/SphereMesh.cpp, include/ppx/geometry.h, projects/08_basic_geometry/main.cpp, projects/09_obj_geometry/main.cpp, projects/10_cube_map/main.cpp, projects/17_primitives/main.cpp, projects/18_arcball_camera/main.cpp, projects/19_camera_fit_scene/main.cpp, projects/20_camera_motion/main.cpp, projects/29_dynamic_rendering/DynamicRendering.cpp, src/ppx/geometry.cpp
Fixes https://github.com/google/bigwheels/issues/303
=> Renames GeometryOptions to GeometryCreateInfo

include/ppx/grfx/grfx_shading_rate.h, include/ppx/grfx/vk/vk_shading_rate.h, src/CMakeLists.txt, src/ppx/grfx/grfx_shading_rate.cpp, src/ppx/grfx/vk/vk_shading_rate.cpp, src/test/CMakeLists.txt, src/test/vk_shading_rate_test.cpp
Add ability to modify ShadingRatePattern as bitmap
=> Add ability to modify ShadingRatePattern as bitmap

include/ppx/grfx/grfx_draw_pass.h, include/ppx/grfx/grfx_helper.h, include/ppx/grfx/grfx_image.h, include/ppx/grfx/grfx_shading_rate.h, include/ppx/grfx/grfx_texture.h, src/ppx/grfx/grfx_draw_pass.cpp, src/ppx/grfx/grfx_texture.cpp, src/ppx/grfx/vk/vk_device.cpp, src/ppx/grfx/vk/vk_image.cpp, src/ppx/grfx/vk/vk_render_pass.cpp
Add subsampledIformat for images and related classes.
=> Add subsampledFormat for Image

include/ppx/application.h
Missed in https://github.com/google/bigwheels/pull/481
=> Remove enableDebugCapture flag

src/ppx/scene/scene_gltf_loader.cpp
There's an early return with error if `IsNull(pGltfPrimitive->indices)` so genTopology will never be `true`. This can be reverted as part of issue #474. Until then, it's confusing and creates a burden for refactoring.
=> Remove genTopology dead code

include/ppx/config.h
Upon inspection, ToString(Result) was missing several cases.
=> Add missing Result values to ToString

.github/workflows/linux-build.yml, .github/workflows/windows-build.yml
Since v3 is going to be deprecated soon.
=> Upgrade actions/upload-artifact from v3 to v4

src/ppx/log.cpp
Add thread annotations to prevent warnings when thread analysis is enabled.
=> misc: add thread annotations
